name: Publish Docker image

on:
  push:
    branches:
      - develop
      - main
    tags:
      - 1.*
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'null2264/firefish'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push (Nightly)
        uses: docker/build-push-action@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name == 'develop' && github.repository == 'null2264/firefish' }}
        with:
          context: .
          push: true
          tags: ghcr.io/null2264/firefish:nightly

      - name: Build and push (Canary)
        uses: docker/build-push-action@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main' && github.repository == 'null2264/firefish' }}
        with:
          context: .
          push: true
          tags: ghcr.io/null2264/firefish:canary

      - name: Build and Push (Release)
        uses: docker/build-push-action@v4
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'null2264/firefish'
        with:
          context: .
          push: true
          tags: |
            ghcr.io/null2264/firefish:latest
            ghcr.io/null2264/firefish:${{ env.VERSION_TAG }}
